version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-stretch-node-browsers

    working_directory: D:\PNa\02 Skola\UPCE\R5ZS\INTWA\moje\bo-web-app

    steps:
      # git pull
      - checkout

      # Download and cache dependencies
      - restore_cache:
          key: wep-app-{{ checksum "pom.xml" }}

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: wep-app-{{ checksum "pom.xml" }}

      # package into a jar
      - run: mvn clean package

      - store_test_results:
          path: target/surefire-reports

      # store raw contents of src code
      - store_artifacts:
          path: target/classes
          destination: sample-springboot-api